version: '3.3'

services:
  codeshare-mongodb:
    image: mongo:latest
    container_name: codeshare-mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: CodeShare
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volumn:/data/db
  codeshare-back:
    image: docker.stw.tw/codeshare-back-image:latest
    container_name: codeshare-back
    restart: always
    ports:
      - 50001:8080
    depends_on:
      - codeshare-mongodb
    links:
      - "codeshare-mongodb:mongodb"
  codeshare-front:
    image: docker.stw.tw/codeshare-front-image:latest
    container_name: codeshare-front
    restart: always
    ports:
      - 50000:80
